name: Generate Artifacts
on: [pull_request]

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Create binary from branch
        run: |
          touch text.txt

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: artifact-name
          path: text.txt